### ISSUE TITLE
non dispatchable handles should be 64 bit

### ISSUE THREAD

**Issue by ratchetfreak** [Rikarin/VulkanizeD#2]
Currently the non-dispatchable handles defined as pointers to opaque structs.

However on every platform they should be a 64 bit integer type

ref: https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fundamentals-objectmodel-overview

```D
private template VK_DEFINE_NON_DISPATCHABLE_HANDLE(string name) {
    enum VK_DEFINE_NON_DISPATCHABLE_HANDLE =struct " ~ name ~ "_T{long value;}; alias " ~ name ~ " = " ~ name ~ "_T;";
}
```

**Comment by Rikarin** [comment]
Fixed
