### ISSUE TITLE
Unable to link the library with dmd

### ISSUE THREAD

**Issue by Flamaros** [Rikarin/VulkanizeD#3]
I got this error message when trying to link the library :
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
E:\Dev\Personal\SwagEngine\lib32\vulkan-1.lib
 Error 43: Not a Valid Library File 

I am using dmd 2.070.0

**Comment by Rikarin** [comment]
Fixed

**Comment by Rikarin** [comment]
Fixed

**Comment by Flamaros** [comment]
Thank you :-)
