### ISSUE TITLE
struct const members still correct

### ISSUE THREAD

**Issue by ParticlePeter** [Rikarin/VulkanizeD#9]
You're binding is still not working, most of the const pointer struct members are improperly used. You've put parentheses around few (even not all!) char of the const (char)* type. Take a look at dvulkan:
https://github.com/ColonelThirtyTwo/dvulkan/blob/master/source/dvulkan/types.d

**Comment by Rikarin** [comment]
https://github.com/Rikarin/VulkanizeD/commit/073ab5ab8e81f58efdc8ab1bf292ea6a12abd104

**Comment by Rikarin** [comment]
Fixed
